modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/Seniorendi/AdvancedPeripherals/issues"
logoFile = "pack.png"
[[mods]]
modId = "advancedperipherals"
version = "${file.jarVersion}"
displayName = "Advanced Peripherals"
displayURL = "https://docs.srendi.de/"
authors = "Srendi"
description = '''
Advanced Peripherals is a mod that adds many useful extensions for CC:Tweaked(Computercraft).
You can communicate with Rerfined Storage, Applied Energistics 2 or with the whole Minecraft world.
Adds things like the Me Bridge, various types of turtles, the Chat Box and more.
'''
[[dependencies.advancedperipherals]]
modId = "forge"
mandatory = true
versionRange = "[43.1.43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "computercraft"
mandatory = true
versionRange = "[1.100.9,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "curios"
mandatory = false
versionRange = "[1.19.2-5.1.1.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "ae2"
mandatory = false
versionRange = "[11.0.0-alpha.6,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "refinedstorage"
mandatory = false
versionRange = "[1.11.0,)"
ordnering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "minecolonies"
mandatory = false
versionRange = "[1.19.2-1.0.1060-ALPHA,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "patchouli"
mandatory = false
versionRange = "[1.19.2-76,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "create"
mandatory = false
versionRange = "[0.5.0.f,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "botania"
mandatory = false
versionRange = "[1.19.2-436-SNAPSHOT,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancedperipherals]]
modId = "mekanism"
mandatory = false
versionRange = "[1.19.2-10.3.5.474,)"
ordering = "NONE"
side = "BOTH"