name: Bug Report
description: Report bugs and problems
body:
  - type: markdown
    attributes:
      value: "Please use the search function before submitting an issue!"
  - type: textarea
    attributes:
      label: Describe
      description: Clearly describe the bug you found
      placeholder: A clear description of what the bug is
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior. Feel free to remove or add steps.
      placeholder:
        1. Do this...
        2. Then hit this...
        3. Then...
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Multiplayer?
      description: Do you play on a server?
      multiple: false
      options:
        - "Yes"
        - "No"
        - "LAN"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Version
      description: What version of advanced peripherals are you using?
      multiple: false
      options:
        - Own compiled build.
        - 1.19.2-0.7.22b (Latest 1.19)
        - 1.19.2-0.7.21b 
        - 1.18.2-0.7.21r (Latest 1.18)
        - 1.18.2-0.7.20r 
        - 1.18.2-0.7.19r
        - 1.16.5-0.7.8r (Latest 1.16)
        - older
    validations:
      required: true
  - type: input
    attributes:
      label: Minecraft, Forge and maybe other related mods versions
      description: What version of Forge and Minecraft do you use?
      placeholder: Forge 39.0.55 Minecraft 1.18.1
    validations:
      required: true
  - type: input
    attributes:
      label: Screenshots or Videos
      description: If applicable, add screenshots or videos to help explain your problem.
  - type: input
    attributes:
      label: Crashlog/log
      description: Use https://gist.github.com or https://pastebin.com to upload your crashlog/log
